name: Bump npm version

on:
  push:
    branches:
      - master

jobs:
  raise-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: "cat package.json"
        run: cat ./package.json
      - name: "Setup Node.js"
        uses: "actions/setup-node@v1"
        with:
          node-version: 12
      - name:  'Automated Version Bump'
        uses:  'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          minor-wording:  ''
          major-wording:  ''
          patch-wording:  'from kukko/package-update/'
          rc-wording:     ''